apiVersion: apps/v1
kind: Deployment
metadata:
  name: stride-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stride-api
  template:
    metadata:
      labels:
        app: stride-api
    spec:
      containers:
      - name: stride-api
        image: stride-mac-registry/stride-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: stride-api
spec:
  selector:
    app: stride-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer