apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  aws_access_key_id: QUtJQVVSTkVPVk81S0NKVVNGNUk=
  aws_secret_access_key: SEMvcUE2SXp2MlRlMHdyTk5kZ1ZMRVNodnZrZkVmYktSTG5aWmE0Mw==
  region: dXMtZWFzdC0x